apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brave-search-mcp-sse.fullname" . }}
  labels:
    {{- include "brave-search-mcp-sse.labels" . | nindent 4 }}
type: Opaque
data:
  brave-api-key: {{ .Values.braveApiKey | b64enc }} 